# Generated by Django 5.2.4 on 2025-07-15 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizationmember",
            name="tasks",
            field=models.ManyToManyField(
                related_name="assignees",
                through="projects.TaskAssignment",
                to="projects.projecttask",
            ),
        ),
    ]
