# Generated by Django 5.2.4 on 2025-07-08 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationmember',
            name='teams',
            field=models.ManyToManyField(related_name='members', through='teams.TeamMembership', to='teams.team'),
        ),
    ]
